# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\x1a\x0cstatus.proto\"$\n\x10UserCheckRequest\x12\x10\n\x08username\x18\x01 \x01(\t23\n\x04User\x12+\n\x05\x43heck\x12\x11.UserCheckRequest\x1a\x0f.StatusResponseb\x06proto3'
  ,
  dependencies=[status__pb2.DESCRIPTOR,])




_USERCHECKREQUEST = _descriptor.Descriptor(
  name='UserCheckRequest',
  full_name='UserCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserCheckRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['UserCheckRequest'] = _USERCHECKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserCheckRequest = _reflection.GeneratedProtocolMessageType('UserCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERCHECKREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserCheckRequest)
  })
_sym_db.RegisterMessage(UserCheckRequest)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=66,
  serialized_end=117,
  methods=[
  _descriptor.MethodDescriptor(
    name='Check',
    full_name='User.Check',
    index=0,
    containing_service=None,
    input_type=_USERCHECKREQUEST,
    output_type=status__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
